#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing 'Holberton School'

apt-get update -y
apt-get install -y nginx

# Ensure nginx listens on all interfaces
sed -i 's/listen 80 default_server;/listen 80 default_server;\n\tlisten [::]:80 default_server;/g' /etc/nginx/sites-available/default

service nginx start

# Add the expected content
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.html

service nginx restart

